### PR TITLE
Multiple images issue, Overwritten of images with other Image of same name, Renaming of Image and then logout issues are solved

### PR DESCRIPTION
**Pull request by gulshan-mittal**
@guptavaibhav18197.  All the commits are cleaned for this pull request.

Issues solved #5 #6 #4

### CODE REVIEW

**Comment by guptavaibhav18197** [comment]
Hi @gulshan-mittal ,

Instead of redoing all the process again by adding a different block [here](https://github.com/RedHenLab/RapidAnnotator-2.0/pull/13/files#diff-16984507633ba92f18fa19c8837b4869R314), the logic should lie [here](https://github.com/RedHenLab/RapidAnnotator-2.0/blob/master/rapidannotator/modules/add_experiment/views.py#L307). 

Also update the value of file.content here itself, so that no changes are required [here](https://github.com/RedHenLab/RapidAnnotator-2.0/pull/13/files#diff-16984507633ba92f18fa19c8837b4869R401). 

Moreover, no changes are required in route *_updateFileName()* and in this [file](rapidannotator/modules/annotate_experiment/templates/annotate_experiment/main.html).


This is simply what you have to do -- if 2 files are - image.png and image.png are uploaded. Simply change it to image_1.png and image_2.png in the start itself. **Note** add underscore too.


Also, from now onwards, instead of making global variables as [here](https://github.com/RedHenLab/RapidAnnotator-2.0/pull/13/files#diff-b3f0340944e43a1180fe44be8f310e00R407) - try to declare variables with local scope.

**Comment by gulshan-mittal** [comment]
@guptavaibhav18197 Thanks for your review and suggestions. Now, the code has been minimized and cleaned. Please review it.

**Comment by guptavaibhav18197** [comment]
Hi @gulshan-mittal ,

Please fetch the currentFile as follows: 
`currentFile = File.query.filter_by(id=newFile.id).first()` 
instead of 
`obj = File.query.order_by(File.id.desc()).first()`

and then use its id to add to name.

Please revert route *_updateFileName()* to its original form. You have deleted all the logic from this route.

What purpose does change in [this](https://github.com/RedHenLab/RapidAnnotator-2.0/pull/13/files#diff-b3f0340944e43a1180fe44be8f310e00L407) line serve?

Thanks,
Vaibhav

**Comment by gulshan-mittal** [comment]
@guptavaibhav18197. You cannot use ``currentFile = File.query.filter_by(id=newFile.id).first()`` as newFile.id is None because its instance has not been commited now in the databse. In earlier commit I am using that thing.

Also now I am using file content to fetch the file so there is no need to update file in the database when the name has been changed. So that is why I have deleted that lines from _updateFileName()
 route as those lines are not necessary.

The purpose is that now we are fetching the file from File.content not from File.name.

**Comment by gulshan-mittal** [comment]
@guptavaibhav18197.  Updated the files changed. Now it is showing 2 files changes because some changes have been merged in file ``annotate_experiment/main.html`` so I have to change it for proper working.

**Comment by guptavaibhav18197** [comment]
@gulshan-mittal ,

Try to follow this logic. 
If user uploads 2 files - image.png & image.png. Then 
file.name   =  image.png & image.png
file.content = image_1.png & image_2.png

Now, if user modifies name of first file to -- modified_image.png Then
file.name   =  modified_image.png & image.png
file.content = modified_image_1.png & image_2.png

Following this logic you will need to fetch file using file.content.

Thanks,
Vaibhav

**Comment by gulshan-mittal** [comment]
Hi @guptavaibhav18197. Thanks for suggesting the idea and logic.

I have implemented the above criterion if still, any error persists please give me feedback.

Thank you.
Gulshan Kumar

**Comment by guptavaibhav18197** [comment]
Hi @gulshan-mittal ,

Thanks for the commit.

**Pull request merged**
